### ISSUE TITLE
Error when saving Fee Structure

### ISSUE THREAD

**Issue by umairsy** [frappe/schools#78]
Steps:
1. Create new Fee Structure for first semester.
2. Duplicated first Fee Structure. In the new Fee Structure, select "Second Semester".
3. Saved Fee Structure.
4. After making some changes, when trying to save Fee Structure, getting error message.

![screen shot 2016-06-23 at 3 33 39 pm](https://cloud.githubusercontent.com/assets/910238/16299671/1d152baa-3959-11e6-8f8f-968d7af7eecb.png)

Console Log:

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 874, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 20, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 250, in save
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 364, in _validate
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 572, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 298, in throw
    msgprint(msg, raise_exception=exc, title=title)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 291, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 264, in _raise_exception
    raise raise_exception, encode(msg)
LinkValidationError: Could not find Academic Term: FS0002`

**Comment by neilLasrado** [comment]
Cant replicate the issue. The error is because the value in Academic Term is incorrect. Let me know in case you face the issue again
